image_width: 2880
image_height: 1860
camera_name: camera_3
camera_matrix:
  rows: 3
  cols: 3
  data: [ 1467.5, 0.0, 1423.6, 0.0, 1471.8, 894.8, 0.0, 0.0, 1.0 ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [ -0.2884, 0.1083, 0, 0, -0.0215 ]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1, 0, 0, 0, 1, 0, 0, 0, 1 ]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 1467.5, 0.0, 1423.6, 0.0, 0.0, 1471.8, 894.8, 0.0, 0.0, 0.0, 1.0, 0.0 ]