/**:
  ros__parameters:
    camera_names: [ "camera_0","camera_1","camera_2","camera_3","camera_4","camera_5","camera_6","camera_7" ]
    camera_0:
      frame_id: CAM_FR/camera_link
      pixel_format: bgr8
      serial_no: 210900353
      camera_info_url: "file:///home/golf/projects/autoware/src/sensor_component/external/arena_camera/config/camera_0.yaml"
      fps: 15
      horizontal_binning: 1
      vertical_binning: 1
      use_default_device_settings: true
      exposure_auto: true
      exposure_target: 187
      gain_auto: true
      gain_target: 1
      gamma_target: 1.0
    camera_1:
      frame_id: CAM_F/camera_link
      pixel_format: bgr8
      serial_no: 210900908
      camera_info_url: "file:///home/golf/projects/autoware/src/sensor_component/external/arena_camera/config/camera1.yaml"
      fps: 15
      horizontal_binning: 1
      vertical_binning: 1
      use_default_device_settings: true
      exposure_auto: true
      exposure_target: 187
      gain_auto: true
      gain_target: 1
      gamma_target: 1.0
    camera_2:
      frame_id: CAM_FL/camera_link
      pixel_format: bgr8
      serial_no: 210900910
      camera_info_url: "file:///home/golf/projects/autoware/src/sensor_component/external/arena_camera/config/front_left_camera.yaml"
      fps: 15
      horizontal_binning: 1
      vertical_binning: 1
      use_default_device_settings: true
      exposure_auto: true
      exposure_target: 187
      gain_auto: true
      gain_target: 1
      gamma_target: 1.0
    camera_3:
      frame_id: CAM_ML/camera_link
      pixel_format: bgr8
      serial_no: 210900347
      camera_info_url: "file:///home/golf/projects/autoware/src/sensor_component/external/arena_camera/config/middle_left_camera.yaml"
      fps: 15
      horizontal_binning: 1
      vertical_binning: 1
      use_default_device_settings: true
      exposure_auto: true
      exposure_target: 187
      gain_auto: true
      gain_target: 1
      gamma_target: 1.0
    camera_4:
      frame_id: CAM_MR/camera_link
      pixel_format: bgr8
      serial_no: 210900914
      camera_info_url: "file:///home/golf/projects/autoware/src/sensor_component/external/arena_camera/config/middle_right_camera.yaml"
      fps: 15
      horizontal_binning: 1
      vertical_binning: 1
      use_default_device_settings: true
      exposure_auto: true
      exposure_target: 187
      gain_auto: true
      gain_target: 1
      gamma_target: 1.0
    camera_5:
      frame_id: CAM_BL/camera_link
      pixel_format: bgr8
      serial_no: 220300080
      camera_info_url: "file:///home/golf/projects/autoware/src/sensor_component/external/arena_camera/config/rear_left_camera.yaml"
      fps: 15
      horizontal_binning: 1
      vertical_binning: 1
      use_default_device_settings: true
      exposure_auto: true
      exposure_target: 187
      gain_auto: true
      gain_target: 1
      gamma_target: 1.0
    camera_6:
      frame_id: CAM_BR/camera_link
      pixel_format: bgr8
      serial_no: 220500928
      camera_info_url: "file:///home/golf/projects/autoware/src/sensor_component/external/arena_camera/config/rear_right_camera.yaml"
      fps: 15
      horizontal_binning: 1
      vertical_binning: 1
      use_default_device_settings: true
      exposure_auto: true
      exposure_target: 187
      gain_auto: true
      gain_target: 1
      gamma_target: 1.0
    camera_7:
      frame_id: CAM_B/camera_link
      pixel_format: bgr8
      serial_no: 210800157
      camera_info_url: "file:///home/golf/projects/autoware/src/sensor_component/external/arena_camera/config/rear_camera.yaml"
      fps: 15
      horizontal_binning: 1
      vertical_binning: 1
      use_default_device_settings: true
      exposure_auto: true
      exposure_target: 187
      gain_auto: true
      gain_target: 1
      gamma_target: 1.0