/**:
  ros__parameters:
    camera_name: "camera_1"
    frame_id: "CAM_F/camera_link"
    pixel_format: bgr8
    serial_no: 210900353
    camera_info_url: "file:///home/ismet/autoware/src/sensor_component/external/arena_camera/config/camera_f_info.yaml"
    fps: 15
    horizontal_binning: 1
    vertical_binning: 1
    use_default_device_settings: true
    # if you use_default_device_settings: true, the following settings are ignored.
    # ROS driver will use the default device settings of the camera.
    exposure_auto: true
    exposure_target: 187
    gain_auto: true
    gain_target: 1
    gamma_target: 1.0