/**:
  ros__parameters:
    camera_name: "front_right_camera"
    frame_id: "CAM_FR/camera_link"
    pixel_format: bgr8
    serial_no: 210900908
    camera_info_url: "file:///home/golf/projects/autoware/src/sensor_component/external/arena_camera/config/half_resolution_cam_info/camera_0.yaml"
    fps: 15
    horizontal_binning: 2
    vertical_binning: 2
    enable_rectifying: true
    enable_compressing: true
    use_default_device_settings: true
    # if you use_default_device_settings: true, the following settings are ignored.
    # ROS driver will use the default device settings of the camera.
    exposure_auto: true
    exposure_target: 187
    gain_auto: true
    gain_target: 1
    gamma_target: 1.0